import { onModalClose } from './js/welcome';
import { onOpenThxModal } from './js/thxModal';
import { onBtnSubmite } from './js/randomGame';
import { showEl } from './js/age';
import { randomVariant } from './js/stone-knives-papyrus';
import { onActiveDarkThem } from './js/theme';
import './js/calculate';
import './js/football';
import './js/carusel';
import './js/cards';
